# Generated by Django 4.2.5 on 2023-10-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thursdayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pcost', models.FloatField()),
                ('pdetails', models.CharField(max_length=100)),
                ('cat', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='log',
            old_name='user_name',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='password',
            new_name='upass',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='confirm_password',
            new_name='ucpass',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='user_name',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='password',
            new_name='upass',
        ),
    ]
