# Generated by Django 4.2.5 on 2023-10-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thursdayapp', '0002_product_rename_user_name_log_uname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=1, upload_to='image '),
            preserve_default=False,
        ),
    ]
